version: '3'

services:
  inethi-user-management-api:
    container_name: inethi-user-management-api
    build: .
    command: bash -c "python manage.py runserver"
    ports:
      - "8000:8000"
    depends_on:
      - inethi-user-management-mysql

  inethi-user-management-mysql:
    container_name: inethi-user-management-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: 'inethi-user-management-api'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "3316:3306"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
