version: '3'

services:
  inethi-user-management-mysql:
    container_name: inethi-user-management-mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'inethi-user-management-api'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - '/mnt/data/inethi_user_management_mysql:/var/lib/mysql'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.djangomysql.entrypoints=websecure"

  inethi-maintainer-backend:
    build:
      context: ./
    container_name: inethi-user-management
    command: bash -c "./wait-for-it.sh inethi-user-management-mysql:3306 -- python manage.py makemigrations && python manage.py migrate && gunicorn inethi_management.wsgi:application --bind 0.0.0.0:8000 --access-logfile '-' --error-logfile '-'"
    depends_on:
      - inethi-user-management-mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.managementBackend.rule=Host(`paum.inethilocal.net`)"
      - "traefik.http.routers.managementBackend.entrypoints=websecure"
      - "traefik.http.services.managementBackend.loadbalancer.server.port=8000"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
