version: '3'

services:
  inethi-user-management-api:
    container_name: inethi-user-management-api
    build: .
    restart: unless-stopped
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - inethi-user-management-mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`${TRAEFIK_API_RULE_DJANGO}.${inethiDN}`)"
      - "traefik.http.routers.django.entrypoints=${TRAEFIK_ENTRYPOINT}"
    volumes:
      - '${DJANGO_MNT}/app:/home/app/webapp'

    ports:
      - "8000:8000"

  inethi-user-management-mysql:
    container_name: inethi-user-management-mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'inethi-user-management-api'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - inethi_user_management_data:/var/lib/mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.djangomysql.entrypoints=${TRAEFIK_ENTRYPOINT}"

volumes:
  inethi_user_management_data:


networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
