version: "3"
services:
  inethi-management-frontend:
    build:
      context: .
    container_name: inethi-management-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.managerFrontend.rule=Host(`manager.inethilocal.net`)"
      - "traefik.http.routers.managerFrontend.entrypoints=websecure"
      - "traefik.http.services.managerFrontend.loadbalancer.server.port=80"
networks:
  default:
    external:
      name: "inethi-bridge-traefik"