version: "3.3"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "inethi-traefikssl"
    restart: unless-stopped
    env_file: "./secrets/secret_keys.env"
    command:
      #- "--log.level=DEBUG"

      # Enable the Trafik dashboard
      - --api.dashboard=true

      # Allow dashboard to use insecure connection
      - --api.insecure=true

      # Tell Traefik to discover containers using the Docker API
      - --providers.docker=true

      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      # Set up an insecure listener that redirects all traffic to TLS
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https


      # Set up the TLS configuration for our websecure listener
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=inethilocal.net"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.inethilocal.net"

      # Diabled certificate verification between traefik and servivces with ssl like Unifi
      - "--serversTransport.insecureSkipVerify=true"

    ports:
      - 80:80
      - 443:443

    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.inethilocal.net`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"


networks:
  default:
    external:
      name: "inethi-bridge-traefik"