version: '3'

services:
  mysql:
      image: mysql:5.7
      container_name: inethi-mysql-keycloak
      restart: always
      environment:
        - "MYSQL_ROOT_PASSWORD=inethi"
        - "MYSQL_DATABASE=keycloak"
        - "MYSQL_USER=inethi"
        - "MYSQL_PASSWORD=inethi"
      volumes:
        - "./keycloak-mysql:/var/lib/mysql"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mysql-keycloak.entrypoints=websecure"

  keycloak:
      image: jboss/keycloak
      container_name: inethi-keycloak
      environment:
        - "HOSTNAME=keycloak.inethilocal.net"
        - "KEYCLOAK_ADMIN=inethi"
        - "KEYCLOAK_ADMIN_PASSWORD=inethi"
        - "KEYCLOAK_USER=inethi-user"
        - "KEYCLOAK_PASSWORD=inethi"
        - "DB_VENDOR=MYSQL"
        - "DB_ADDR=inethi-mysql-keycloak"
        - "DB_DATABASE=keycloak"
        - "DB_USER=inethi"
        - "DB_PASSWORD=inethi"
        - "PROXY_ADDRESS_FORWARDING=true"

      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.inethilocal.net`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"


networks:
  default:
    external:
      name: "inethi-bridge-traefik"